GET http://localhost:8080/spring-mvc-app/api/v1/user/all
Authorization: Basic admin 123

###

GET http://localhost:8080/spring-mvc-app/api/v1/user/4
Authorization: Basic admin 123

###

POST http://localhost:8080/spring-mvc-app/api/v1/user
Authorization: Basic super_admin 123
Content-Type: application/json

  {
    "username": "igor456",
    "age": 2,
    "password": 123,
    "repeatPassword": 123,
    "roles": []
  }

###

PUT http://localhost:8080/spring-mvc-app/api/v1/user
Content-Type: application/json

{
  "id": 18,
  "username": "cvb-cvb",
  "age": 99
}

###

DELETE http://localhost:8080/spring-mvc-app/api/v1/user/11